version: '3.8'

services:
  cdn:
    image: nestjs-cdn-server:latest
    build:
      context: .
      target: production
    ports:
      - '${PORT:-8024}:${PORT:-3000}'
    env_file:
      - .env
    volumes:
      - uploads:/app/public/images

volumes:
  uploads:
